name: CreateFlatpak

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  flatpak:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: InstallFlatpak
      run: |
        sudo apt install flatpak flatpak-builder
        
    - name: SetupFlatpak
      run: |
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install flathub org.gnome.Platform//3.38 org.gnome.Sdk//3.38 -y
        
    - name: BuildFlatpak
      run: |
        flatpak-builder --repo=repo --force-clean build-dir org.gramps_project.Gramps.yml
        
    - name: BuildBundle
      run: |
        flatpak build-bundle repo gramps.flatpak org.gramps_project.Gramps
        
    - name: UploadBundle
      uses: actions/upload-artifact@v2
      with:
        name: gramps.flatpak
        path: gramps.flatpak
