name: CreateFlatpak

on:
  push:
    branches:
      - 'main'
    paths:
      - 'org.gramps_project.Gramps.yml'
  workflow_dispatch:

jobs:
  flatpak:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: InstallFlatpak
      run: |
        sudo add-apt-repository ppa:flatpak/stable
        sudo apt update
        sudo apt install flatpak flatpak-builder python3-pip

    - name: SetupFlatpak
      run: |
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install flathub org.gnome.Platform//44 org.gnome.Sdk//44 -y

    - name: BuildFlatpak
      run: |
        flatpak-builder --repo=repo --force-clean build-dir org.gramps_project.Gramps.yml

    - name: BuildBundle
      run: |
        flatpak build-bundle repo gramps.flatpak org.gramps_project.Gramps

    - name: UploadBundle
      uses: actions/upload-artifact@v3
      with:
        name: gramps.flatpak
        path: gramps.flatpak

    - name: Archive-as-Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: gramps.flatpak
        tag_name: gramps.flatpak
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Upload-Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
#        upload_url: ${{ github.ref.upload_url }}
        asset_path: ./bin/flatpak.gramps.flatpak
        asset_name: gramps.flatpak
        asset_content_typs: application/flatpak
